import pandas as pd

# process_data
AFRICAN_COUNTRIES = [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "DR Congo (Zaire)",
    "Democratic Republic of Congo",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Ivory Coast",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Reunion",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
    "eSwatini",
]
START_DATE = pd.Timestamp("1997-01-01")
END_DATE = pd.Timestamp("2023-12-31")

# combine_sequences
THR_TIMEOVERLAP = 0.7
MAX_DIST_KM = 200
MAX_SECOND_DEGREE_DIST = 300

# extract_sequences in all sequence classes
DEFAULT_METRIC_AGG_MAP = {
    "event_id_list": "list",
    "event_id_cnty": "count",
    "disorder_type": "list",
    "latitude": "mean",
    "longitude": "mean",
    "fatalities": "sum",
    "actor1": "first",
    "actor2": "first",
    "actor1_id": "first",
    "actor2_id": "first",
    "source_dataset": "first",
    "dyad": "unique count",
    "gid": "unique count",
    "agri_gc": "mean",
    "aquaveg_gc": "mean",
    "barren_gc": "mean",
    "forest_gc": "mean",
    "herb_gc": "mean",
    "shrub_gc": "mean",
    "urban_gc": "mean",
    "water_gc": "mean",
    "ttime_mean": "mean",
    "dist_border_km_2004": "mean",
    "dist_capital_km_2004": "mean",
}
